ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = DBUSER;

CREATE TABLE users (
    id VARCHAR2(20 CHAR) PRIMARY KEY,
    password_hash VARCHAR2(255 CHAR) NOT NULL,
    password_salt RAW(16) NOT NULL,
    full_name VARCHAR2(255 CHAR) NOT NULL,
    email VARCHAR2(255 CHAR),
    phone_number VARCHAR2(20 CHAR),
    age NUMBER(3),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE accounts (
    id VARCHAR2(20 CHAR) PRIMARY KEY,
    user_id VARCHAR2(20 CHAR) NOT NULL,
    balance NUMBER(15) DEFAULT 0 NOT NULL,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_accounts_balance
        CHECK (balance >= 0),
    CONSTRAINT fk_accounts_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


CREATE TABLE transactions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id VARCHAR2(20 CHAR) NOT NULL,
    account_id_transfer VARCHAR2(20 CHAR),
    group_id_transfer VARCHAR2(36 CHAR),
    type VARCHAR2(20 CHAR) NOT NULL,
    amount NUMBER(15) NOT NULL,
    balance_after NUMBER(15) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_transactions_type
        CHECK (type IN ('DEPOSIT', 'WITHDRAW', 'TRANSFER_OUT', 'TRANSFER_IN')),
    CONSTRAINT fk_transactions_account
        FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_transactions_account_transfer
        FOREIGN KEY (account_id_transfer) REFERENCES accounts(id) ON DELETE SET NULL
);


CREATE SEQUENCE account_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE transaction_group_id_seq START WITH 1 INCREMENT BY 1;


COMMIT;